Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -7,12 +7,6 @@ set -o errexit    # always exit on error
 set -o pipefail   # don't ignore exit codes when piping output
 unset GIT_DIR     # Avoid GIT_DIR leak from previous build steps
 
-# Set the type of build
-if [ ! -f "${ENV_DIR}/BUILD_TYPE" ]; then
-    echo "BUILD_TYPE was not set. Aborting"
-    exit 1
-fi
-
 ### Constants
 
 # This is used by the buildpack stdlib for metrics
@@ -25,6 +19,12 @@ BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
 BP_DIR=$(cd "$(dirname "${0:-}")"; cd ..; pwd)
+
+# Set the type of build
+if [ ! -f "${ENV_DIR}/BUILD_TYPE" ]; then
+    echo "BUILD_TYPE was not set. Aborting"
+    exit 1
+fi
 
 ### Load dependencies
 
